#!/bin/bash

############################################################################
#
# Copyright (c) 2013 - NeoTeam (neocooler29@gmail.com)
#
# TNT(Tools NeoTeam) is 100% free.  This script file is intended for 
# personal and/or educational use only.  
# It may not be duplicated for monetary benefit or any other purpose 
# Without the permission of the developer.
#
############################################################################

version=$1

source script/colors
echo -e "$NORMALE"

while : 
do
	clear
	echo -e "$Cyan" "============================================================" "$NORMAL"
	echo -e "     $Green_BU"" ToolsNeoTeam V.$version - by NeoCooler aka krisjanne" "$NORMAL"
	echo -e "$Cyan" "============================================================" "$NORMAL"
	echo -e "$Cyan" "->$NORMAL$White ANDROID MENU$NORMAL"
	echo -e "$Magenta"
	echo -e "     3 -$White_K Dsixda's Android Kitchen$Magenta"
	echo -e "     4 -$White_K Run Kitchen$Magenta"
	echo
	echo -e "     5 -$White_K Add Repository Ubuntu SDK$Magenta"
	echo -e "     6 -$White_K Install Ubuntu SDK$Magenta"
	echo
	echo -e "     x -$White_K Return MAIN MENU$Magenta"
	echo -e "$NORMAL"
	echo -e -n "$Yellow" " Choose option:" "$White_B"
	read tntopt
	echo
	echo -e "$NORMAL"
	 
	case "$tntopt" in
		3 ) clear; sudo apt-get install git-core; git clone git://github.com/dsixda/Android-Kitchen.git ~/kitchen; clear; continue;;
	    	4 ) clear; cd ~/kitchen; ./menu; clear; continue;;
		5 ) clear; sudo add-apt-repository ppa:ubuntu-sdk-team/ppa; clear; continue;;
		6 ) clear; sudo apt-get install ubuntu-sdk; clear; continue;;
		x ) clear; exit 1;;
		* ) echo -e "$Red_B" " Invalid option" "$NORMAL";;
	esac

	script/press_enter

done
