#!/bin/bash

############################################################################
#
# Copyright (c) 2013 - NeoTeam (neocooler29@gmail.com)
#
# TNT(Tools NeoTeam) is 100% free.  This script file is intended for 
# personal and/or educational use only.  
# It may not be duplicated for monetary benefit or any other purpose 
# Without the permission of the developer.
#
############################################################################

version=0.010



if [ ! -e menu ]
then
  echo
  echo "Ensure you run this file from the SAME folder as where it was"
  echo "installed, otherwise TNT will have problems run."
  echo "After you 'cd' to TNT folderStart TNT"
  echo "Start TNT with the ./menu command!!!"
  exit 0
fi

chmod 755 script/*
script/check_install_dir

if [ "$?" == "1" ]
then
  exit 0
fi

while :
do
	clear
	online_vers=`script/check_update`
	rm -f Last_CHANGELOG
	last_vers=`echo $online_vers | sed -e 's/.*Version[ ]*\([0-9]*.[0-9]*\) (.*/\1/g' -e 's/[ ]*//g'`

  	curr_major=`echo $version | sed 's/\([0-9]*\).[0-9]*/\1/'`
  	curr_minor=`echo $version | sed 's/[0-9]*.//'`

  	last_major=`echo $last_vers | sed 's/\([0-9]*\).[0-9]*/\1/'`
  	last_minor=`echo $last_vers | sed 's/[0-9]*.//'`

  	update=1

  	#
  	# Compare our version with version online
 	#
  	if [ $curr_major -gt $last_major ]
  	then
  	  update=0
 	 else

 	  if [ $curr_major -eq $last_major ]
 	   then
 	    if [ $curr_minor -ge $last_minor ]
  	    then
  	      update=0
  	   fi
 	   fi
 	 fi
 	 if [ $update == 0 ] 
 	 then
 	   info=
 	 else
	echo -e "\033[34m==InfoBox===================================================\033[0m"
	echo -e "\033[34m|\033[32mNew Update online (V.$last_vers). Option (u) = Direct UPDATE\033[0m"
	 fi
	echo -e "\033[34m============================================================\033[0m"
	echo "          TNT V.$version - by NeoCooler aka krisjanne"
	echo -e "\033[34m============================================================\033[0m"
	echo "-> MAIN MENU"
	echo
	echo "     1 - Update Menu"
	echo "     2 - Applications Menu"
	echo "     3 - "
	echo
	echo "     b - Android build AOSP"
	echo
	echo "     k - Run Dsixda's Android Kitchen"
	echo
	echo "     x - Exit"
	echo
	echo
	echo -e -n "\033[32m Choose option: \033[0m"
	read tntopt
	echo
	echo

    if [ "$?" != "1" ]
      then
	case "$tntopt" in
	    1 ) clear; script/update $version; continue;;
	    2 ) clear; script/app $version; continue;;
	    b ) clear; script/build_aosp $version; continue;;
	    u ) clear; script/updater $version; continue;;
	    k ) clear; cd ~/kitchen; ./menu; clear; continue;;
	    x ) clear; echo -e "\033[31mGoodbey !\033[0m"; echo; exit 1;;
	    * ) echo -e "\033[31m Invalid option\033[0m";;
	esac
    fi
  
    script/press_enter

done

exit 0;
