#!/bin/bash

############################################################################
#
# Copyright (c) 2013 - NeoTeam (neocooler29@gmail.com)
#
# TNT(Tools NeoTeam) is 100% free.  This script file is intended for 
# personal and/or educational use only.  
# It may not be duplicated for monetary benefit or any other purpose 
# Without the permission of the developer.
#
############################################################################

version=0.2

chmod 755 scripts/*

while :
do
	clear

	echo -e "\033[34m============================================================\033[0m"
	echo "          TNT V.$version - by NeoCooler aka krisjanne"
	echo -e "\033[34m============================================================\033[0m"
	echo "-> MAIN MENU"
	echo
	echo "     1 - Update Menu"
	echo "     2 - Applications Menu"
	echo
	echo "     k - Run Dsixda's Android Kitchen"
	echo
	echo "     x - Exit"
	echo
	echo
	echo -e -n "\033[32m Choose option:\033[0m"
	read tntopt
	echo
	echo
	echo

	case "$tntopt" in
	    1 ) clear; script/update $version; continue;;
	    2 ) clear; script/app $version; continue;;
	    k ) clear; cd ~/kitchen; ./menu; clear; continue;;
	    x ) clear; echo "Goodbey !"; echo; exit 1;;
	    * ) clear; echo "Invalid option"; continue;;
	esac
done

exit 0;
