#!/bin/bash
clear

echo -e $MAGENTA"    <= !!! Welcome to TNT ONE, one command all is done !!! =>"$NORMAL

echo -e $BLUE"# Debug Return:"$NORMAL

#Check root
source scripts/check_root

#Fixe Permission
sudo chmod -R 777 scripts/*
echo -e $GREEN"-> Permissions Verified"$NORMAL

#Color injection
source scripts/colors
echo -e $GREEN"-> Add Colorisation for Terminal Verified"$NORMAL

#System Functions
source scripts/functions_system
echo -e $GREEN"-> Add All System Functions Verified"$NORMAL

#Ajust Terminal Dimension
echo -ne '\e[8;13;93t'
echo -e $GREEN"-> Terminal Dimension Verified"$NORMAL

#Icone injection
source scripts/icones
echo -e $GREEN"-> Add some links to icone from system Verified"$NORMAL

#System info
source info_system
echo -e $GREEN"-> Information system Verified"$NORMAL

#Fonctions
source scripts/functions
echo -e $GREEN"-> Ohers Functions Verified"$NORMAL

#Check Distro
source scripts/check_distro
echo -e $GREEN"-> Distro Verified"$NORMAL

#Check Architecture
source scripts/check_archi
echo -e $GREEN"-> Archi Verified"$NORMAL

#Check programm open
source scripts/check_open
echo -e $GREEN"-> Open Verified"$NORMAL

#Check Internet connection
source scripts/check_connection

#Check needed Package
source scripts/check_package
echo -e $GREEN"-> Package Verified"$NORMAL

#Check for update
source scripts/check_update
echo -e $GREEN"-> Update Verified"$NORMAL

#Title TNT
source scripts/title

echo -e $BLUE"#"
			echo -e $BLUE"#$RED Installer Info:"
			echo -e $BLUE"#$NORMAL"

sudo apt-get -qq update
echo -e $GREEN"-> Update all Package"$NORMAL
GimpPrep
echo -e $GREEN"-> Prepare Gimp files"$NORMAL
GoogleChromePrep
echo -e $GREEN"-> Prepare Google Chrome files"$NORMAL
sudo apt-get -qq update
echo -e $GREEN"-> Update all Package"$NORMAL
Cheese

Gimp

GoogleChrome

Nvidia

GoogleMusicManager


echo -e $BLUE"#"
			echo -e $BLUE"#$RED Update Info:"
			echo -e $BLUE"#$NORMAL"
			
sudo apt-get -qq update
echo -e $GREEN"-> Update all Package"$NORMAL
sudo apt-get -qq dist-upgrade
echo -e $GREEN"-> Upgrade Distro"$NORMAL
sudo apt-get -qq upgrade
echo -e $GREEN"-> Upgrade All"$NORMAL
sudo apt-get -qq update
echo -e $GREEN"-> Update all Package"$NORMAL

echo -e $BLUE"#"
			echo -e $BLUE"#$RED Cleanner Info:"
			echo -e $BLUE"#$NORMAL"
			
sudo apt-get -qq update
echo -e $GREEN"-> Update all Package"$NORMAL
Oldpack
echo -e $GREEN"-> Clean Old Package"$NORMAL
Cachepack
echo -e $GREEN"-> Clean Cache"$NORMAL

