#!/bin/bash

#############################################################################################
#  -----------------------------------                                                      #
#  | ######## ###   ## ########      | Copyright (c) 2013 - NeoTeam (neocooler29@gmail.com) #
#  |    ##    ####  ##    ##         ---                                                    #
#  |    ##    ## ## ##    ##            |-¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸           #
#  |    ##    ##  ####    ##         ---    ``` ``` ``` ``` ``` ``` ``` ``` ``` ```***      #
#  |    ##    ##   ###    ##         | TNT(Tools NeoTeam) is 100% free.                     #
#  ----------------------------------- It may not be duplicated for monetary benefit or any #
#                                    other purpose Without the permission of the developer. #
#############################################################################################

version=$1

source script/colors
echo -e "$NORMALE"

source script/check_root

while : 
do
	clear
	echo -e "$Cyan" "============================================================" "$NORMAL"
	echo -e "     $Green_BU"" ToolsNeoTeam V.$version - by NeoCooler aka krisjanne" "$NORMAL"
	echo -e "$Cyan" "============================================================" "$NORMAL"
	echo -e "$Cyan" "->$NORMAL$White GNOME INSTALL$NORMAL"
	echo -e "$Magenta"
	echo -e "     i -$White_K Install Gnome$Magenta"
	echo
	echo -e "     r -$White_K Remouve Gnome$Magenta"
	echo
	echo -e "     x -$White_K Return APPLICATIONS MENU$Magenta"
	echo -e "$NORMAL"
	echo -e -n "$Yellow" " Choose option:" "$White_B"
	read tntopt
	echo
	echo -e "$NORMAL"
	 
	case "$tntopt" in
	    i ) sudo add-apt-repository ppa:gnome3-team/gnome3;
	        sudo apt-get update;
		sudo apt-get upgrade;
	        sudo apt-get install gnome-shell ubuntu-gnome-desktop;;
	    r ) clear; sudo apt-get autoremove --purge gnome-shell ubuntu-gnome-desktop;;
	    x ) clear; exit 0;;
	    * ) echo -e "$Red_B" " Invalid option" "$NORMAL";;
	esac
    script/press_enter
done
