#!/bin/bash

#############################################################################################
#  -----------------------------------                                                      #
#  | ######## ###   ## ########      | Copyright (c) 2013 - NeoTeam (neocooler29@gmail.com) #
#  |    ##    ####  ##    ##         ---                                                    #
#  |    ##    ## ## ##    ##            |-¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸           #
#  |    ##    ##  ####    ##         ---    ``` ``` ``` ``` ``` ``` ``` ``` ``` ```***      #
#  |    ##    ##   ###    ##         | TNT(Tools NeoTeam) is 100% free.                     #
#  ----------------------------------- It may not be duplicated for monetary benefit or any #
#                                    other purpose Without the permission of the developer. #
#############################################################################################

version=$1

source script/colors
echo -e "$NORMALE"

while : 
do
	clear
	echo -e "$Cyan" "============================================================" "$NORMAL"
	echo -e "     $Green_BU"" ToolsNeoTeam V.$version - by NeoCooler aka krisjanne" "$NORMAL"
	echo -e "$Cyan" "============================================================" "$NORMAL"
	echo -e "$Cyan" "->$NORMAL$White KDE INSTALL$NORMAL"
	echo -e "$Magenta"
	echo -e "     i -$White_K Install KDE$Magenta"
	echo -e "     a -$White_K Install/Update Amarok$Magenta"
	echo
	echo -e "     r -$White_K Remove KDE$Magenta"
	echo
	echo -e "     x -$White_K Return APPLICATIONS MENU$Magenta"
	echo -e "$NORMAL"
	echo -e -n "$Yellow" " Choose option:" "$White_B"
	read tntopt
	echo
	echo -e "$NORMAL"
	 
	case "$tntopt" in
	    i ) sudo add-apt-repository ppa:kubuntu-ppa/backports; 
		sudo apt-get update; sudo apt-get  install kde-workspace;;
	    a ) sudo apt-get install amarok;;
	    r ) sudor apt-get autoremove --purge kde-workspace;;
	    x ) exit 0;;
	    * ) echo -e "$Red_B" " Invalid option" "$NORMAL";;
	esac
    script/press_enter
done
