#!/bin/bash

############################################################################
#
# Copyright (c) 2013 - NeoTeam (neocooler29@gmail.com)
#
# TNT(Tools NeoTeam) is 100% free.  This script file is intended for 
# personal and/or educational use only.  
# It may not be duplicated for monetary benefit or any other purpose 
# Without the permission of the developer.
#
############################################################################

version=$1

app_b_title="GIT COLA"
app_title="Git Cola"

source script/colors
echo -e "$NORMALE"

while : 
do
	clear
	echo -e "$Cyan" "============================================================" "$NORMAL"
	echo -e "     $Green_BU"" ToolsNeoTeam V.$version - by NeoCooler aka krisjanne" "$NORMAL"
	echo -e "$Cyan" "============================================================" "$NORMAL"
	echo -e "$Cyan" "->$NORMAL$White $app_b_title INSTALL$NORMAL"
	echo -e "$Magenta"
	echo -e "$White_K Your Actual version is:$Red_B"
	git-cola --version
	echo -e "$Magenta"
	echo -e "     i -$White_K Install $app_title $Magenta"
	echo -e "     u -$White_K Update $app_title $Magenta"
	echo
	echo -e "     o -$White_K Open $app_title $Magenta"
	echo
	echo -e "     r -$White_K Remouve $app_title $Magenta"
	echo
	echo -e "     x -$White_K Return APPLICATIONS MENU$Magenta"
	echo -e "$NORMAL"
	echo -e -n "$Yellow" " Choose option:" "$White_B"
	read tntopt
	echo
	echo -e "$NORMAL"
	 
	case "$tntopt" in
	    i ) sudo apt-get install -y git-cola;;
	    u ) sudo apt-get install -y git-cola;;
	    o ) git-cola;clear; continue;;
	    r ) sudo apt-get autoremove --purge -y git-cola;;
	    x ) clear; exit 0;;
	    * ) echo -e "$Red_B" " Invalid option" "$NORMAL";;
	esac
    script/press_enter
done
