#!/bin/bash

#############################################################################################
#  -----------------------------------                                                      #
#  | ######## ###   ## ########      | Copyright (c) 2013 - NeoTeam (neocooler29@gmail.com) #
#  |    ##    ####  ##    ##         ---                                                    #
#  |    ##    ## ## ##    ##            |-¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸           #
#  |    ##    ##  ####    ##         ---    ``` ``` ``` ``` ``` ``` ``` ``` ``` ```***      #
#  |    ##    ##   ###    ##         | TNT(Tools NeoTeam) is 100% free.                     #
#  ----------------------------------- It may not be duplicated for monetary benefit or any #
#                                    other purpose Without the permission of the developer. #
#############################################################################################
NORMAL="\\033[0;0m"

Black="\\033[0;30m"
Black_B="\\033[1;30m"
Black_U="\\033[4;30m"
Black_K="\\033[5;30m"
Black_R="\\033[7;30m"
BLACK="\\033[40m"

Red="\\033[0;31m"
Red_B="\\033[1;31m"
Red_U="\\033[4;31m"
Red_K="\\033[5;31m"
Red_R="\\033[7;31m"
RED="\\033[41m"

Green="\\033[0;32m"
Green_B="\\033[1;32m"
Green_U="\\033[4;32m"
Green_BU="\\033[1;4;32m"
Green_K="\\033[5;32m"
Green_R="\\033[7;32m"
GREEN="\\033[42m"

Yellow="\\033[0;33m"
Yellow_B="\\033[1;33m"
Yellow_U="\\033[4;33m"
Yellow_K="\\033[5;33m"
Yellow_R="\\033[7;33m"
YELLOW="\\033[43m"

Blue="\\033[0;34m"
Blue_B="\\033[1;34m"
Blue_U="\\033[4;34m"
Blue_K="\\033[5;34m"
Blue_R="\\033[7;34m"
BLUE="\\033[44m"

Magenta="\\033[0;35m"
Magenta_B="\\033[1;35m"
Magenta_U="\\033[4;35m"
Magenta_K="\\033[5;35m"
Magenta_R="\\033[7;35m"
MAGENTA="\\033[45m"

Cyan="\\033[0;36m"
Cyan_B="\\033[1;36m"
Cyan_U="\\033[4;36m"
Cyan_K="\\033[5;36m"
Cyan_R="\\033[7;36m"
CYAN="\\033[46m"

White="\\033[0;37m"
White_B="\\033[1;37m"
White_U="\\033[4;37m"
White_BU="\\033[1;4;37m"
White_K="\\033[5;37m"
White_R="\\033[7;37m"
WHITE="\\033[47m"

