#!/bin/bash

#############################################################################################
#  -----------------------------------                                                      #
#  | ######## ###   ## ########      | Copyright (c) 2013 - NeoTeam (neocooler29@gmail.com) #
#  |    ##    ####  ##    ##         ---                                                    #
#  |    ##    ## ## ##    ##            |-¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸           #
#  |    ##    ##  ####    ##         ---    ``` ``` ``` ``` ``` ``` ``` ``` ``` ```***      #
#  |    ##    ##   ###    ##         | TNT(Tools NeoTeam) is 100% free.                     #
#  ----------------------------------- It may not be duplicated for monetary benefit or any #
#                                    other purpose Without the permission of the developer. #
#############################################################################################

version=$1

source script/colors
echo -e "$NORMALE"

source script/check_root

while : 
do
	clear
	echo -e "$Cyan" "============================================================" "$NORMAL"
	echo -e "     $Green_BU"" ToolsNeoTeam V.$version - by NeoCooler aka krisjanne" "$NORMAL"
	echo -e "$Cyan" "============================================================" "$NORMAL"
	echo -e "$Cyan" "->$NORMAL$White JAVA INSTALL$NORMAL"
	echo -e "$Magenta"
	echo -e "$White_K Folow step by step:"
	echo -e "$Magenta"
	echo -e "     1 -$White_K Add Repository source$Magenta"
	echo -e "     2 -$White_K Install Java 7$Magenta"
	echo
	echo -e "$White_K Switch to another version:$Magenta"
	echo
	echo -e "     3 -$White_K Change Java Version$Magenta"
	echo -e "     4 -$White_K Change Javac Version$Magenta"
	echo -e "     5 -$White_K Chagne Java Plugin Version$Magenta"
	echo -e "     6 -$White_K Change Javaws Version$Magenta"
	echo
	echo -e "     x -$White_K Return APPLICATIONS MENU$Magenta"
	echo -e "$NORMAL"
	echo -e -n "$Yellow" " Choose option:" "$White_B"
	read tntopt
	echo
	echo -e "$NORMAL"
	 
	case "$tntopt" in
	    1 ) sudo add-apt-repository ppa:webupd8team/java;;
	    2 ) sudo apt-get install oracle-java7-installer;;
	    3 ) sudo update-alternatives --config java;;
	    4 ) sudo update-alternatives --config javac;;
	    5 ) sudo update-alternatives --config mozilla-javaplugin.so;;
	    6 ) sudo update-alternatives --config javaws;;
	    x ) clear; exit 0;;
	    * ) echo -e "$Red_B" " Invalid option" "$NORMAL";;
	esac
    script/press_enter
done
