#!/bin/bash

#############################################################################################
#  -----------------------------------                                                      #
#  | ######## ###   ## ########      | Copyright (c) 2013 - NeoTeam (neocooler29@gmail.com) #
#  |    ##    ####  ##    ##         ---                                                    #
#  |    ##    ## ## ##    ##            |-¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸           #
#  |    ##    ##  ####    ##         ---    ``` ``` ``` ``` ``` ``` ``` ``` ``` ```***      #
#  |    ##    ##   ###    ##         | TNT(Tools NeoTeam) is 100% free.                     #
#  ----------------------------------- It may not be duplicated for monetary benefit or any #
#                                    other purpose Without the permission of the developer. #
#############################################################################################

version=$1

source script/colors
echo -e "$NORMALE"

while : 
do
	clear
	echo -e "$Cyan" "============================================================" "$NORMAL"
	echo -e "     $Green_BU"" ToolsNeoTeam V.$version - by NeoCooler aka krisjanne" "$NORMAL"
	echo -e "$Cyan" "============================================================" "$NORMAL"
	echo -e "$Cyan" "->$NORMAL$White NVIDIA INSTALL$NORMAL"
	echo -e "$Magenta"
	echo -e "$White_K Folow step by step:"
	echo -e "$Magenta"
	echo -e "     1 -$White_K Install Linux-Source$Magenta"
	echo -e "     2 -$White_K Install Linux-Header-generic$Magenta"
	echo -e "     3 -$White_K Install Nvidia Current Updates$Magenta"
	echo
	echo -e "$White_K Restart after installation:$Magenta"
	echo -e "     o -$White_K Restart$Magenta"
	echo
	echo -e "     r -$White_K Remouve All ($Red_K Start here if you come form another version$White_K )$Magenta"
	echo
	echo -e "     x -$White_K Return APPLICATIONS MENU$Magenta"
	echo -e "$NORMAL"
	echo -e -n "$Yellow" " Choose option:" "$White_B"
	read tntopt
	echo
	echo -e "$NORMAL"
	 
	case "$tntopt" in
	    1 ) sudo apt-get install linux-source;;
	    2 ) sudo apt-get install linux-headers-generic;;
	    3 ) sudo apt-get install nvidia-current-updates;;
	    o ) sudo reboot;;
	    r ) sudo apt-get purge nvidia-current nvidia-current-updates nvidia-experimental-304;;
	    x ) clear; exit 0;;
	    * ) echo -e "$Red_B" " Invalid option" "$NORMAL";;
	esac
    script/press_enter
done
