#!/bin/bash

#############################################################################################
#  -----------------------------------                                                      #
#  | ######## ###   ## ########      | Copyright (c) 2013 - NeoTeam (neocooler29@gmail.com) #
#  |    ##    ####  ##    ##         ---                                                    #
#  |    ##    ## ## ##    ##            |-¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸           #
#  |    ##    ##  ####    ##         ---    ``` ``` ``` ``` ``` ``` ``` ``` ``` ```***      #
#  |    ##    ##   ###    ##         | TNT(Tools NeoTeam) is 100% free.                     #
#  ----------------------------------- It may not be duplicated for monetary benefit or any #
#                                    other purpose Without the permission of the developer. #
#############################################################################################

version=$1

source script/colors
echo -e "$NORMALE"

while : 
do
clear
echo -e "$Cyan" "============================================================" "$NORMAL"
echo -e "     $Green_BU"" ToolsNeoTeam V.$version - by NeoCooler aka krisjanne" "$NORMAL"
echo -e "$Cyan" "============================================================" "$NORMAL"
echo -e "$Cyan" "->$NORMAL$White RELEASE UPGRADE$NORMAL"
echo -e "$Magenta"
echo -e "     1 -$White_K Check Stable Release.$Magenta"
echo -e "     2 -$White_K Check Development Release.$Magenta"
echo -e "     3 -$White_K Check Last Release.$Magenta"
echo
echo -e "     x -$White_K Return MAIN MENU.$Magenta"
echo -e "$NORMAL"
echo -e -n "$Yellow" " Choose option:" "$White_B"
read tntopt
echo
echo -e "$NORMAL"

if [ "$?" != "1" ]
then
case "$tntopt" in
	1 ) clear; sudo do-release-upgrade -p;;
	2 ) clear; sudo do-release-upgrade -d;;
	3 ) clear; sudo do-release-upgrade -c;;
	x ) clear; exit 0;;
	* ) echo -e "\033[31m Invalid option\033[0m";;
esac
fi
script/press_enter

done
exit 0;
