#!/bin/bash

#############################################################################################
#  -----------------------------------                                                      #
#  | ######## ###   ## ########      | Copyright (c) 2013 - NeoTeam (neocooler29@gmail.com) #
#  |    ##    ####  ##    ##         ---                                                    #
#  |    ##    ## ## ##    ##            |-¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸           #
#  |    ##    ##  ####    ##         ---    ``` ``` ``` ``` ``` ``` ``` ``` ``` ```***      #
#  |    ##    ##   ###    ##         | TNT(Tools NeoTeam) is 100% free.                     #
#  ----------------------------------- It may not be duplicated for monetary benefit or any #
#                                    other purpose Without the permission of the developer. #
#############################################################################################

curr_vers=$1

source script/colors
echo -e "$NORMALE"

source script/check_root

echo -e "$Cyan" "============================================================" "$NORMAL"
echo -e "     $Green_BU"" ToolsNeoTeam V.$curr_vers - by NeoCooler aka krisjanne" "$NORMAL"
echo -e "$Cyan" "============================================================" "$NORMAL"
echo -e "$Cyan" "->$NORMAL$White ABOUT TNT$NORMAL"
echo -e "$Magenta"
echo -e "------------------------------------------------------------"
echo
echo -e "$White_K  For support/community   :$Red http://m1p.fr/xCU$Magenta"
echo -e "$White_K  For Paypal donations    :$Red neocooler29@gmail.com$Magenta"
echo
echo -e "------------------------------------------------------------"
echo
echo
    while [ "$check_update" != "y" ] 
    do
        echo -e -n "$Yellow" "Check online for updates (y/n)?:" "$White_B"
        read check_update
    	case "$check_update" in
		y ) echo;;
		n ) echo; exit 0;;
		* ) echo -e "$Red_B" " Invalid option" "$NORMAL";;
    	esac
    done

    echo 
    echo -e "$Red_B" "Searching for updates ..." "$NORMAL"

    online_vers=`update/check_update`
 
    last_vers=`echo $online_vers | sed -e 's/.*Version[ ]*\([0-9]*.[0-9]*\) (.*/\1/g' -e 's/[ ]*//g'`

    curr_major=`echo $curr_vers | sed 's/\([0-9]*\).[0-9]*/\1/'`
    curr_minor=`echo $curr_vers | sed 's/[0-9]*.//'`

    last_major=`echo $last_vers | sed 's/\([0-9]*\).[0-9]*/\1/'`
    last_minor=`echo $last_vers | sed 's/[0-9]*.//'`

    update=1

    #
    # Compare our version with version online
    #
    if [ $curr_major -gt $last_major ]
    then
    update=0
    else

      if [ $curr_major -eq $last_major ]
      then
        if [ $curr_minor -ge $last_minor ]
        then
          update=0
        fi
      fi
    fi
    if [ $update == 0 ] 
    then
    echo -e "$Red_B" "Last version online is $last_vers.  No update required." "$NORMAL"
    else
    echo
    echo -e "$Red_B" "An update was found ($last_vers)." "$NORMAL"
    echo
    echo

    	echo -e -n "$Yellow" "View CHANGELOG-$last_vers (y/n)? (default: n):" "$White_B"
    	read view_changelog
	if [ "$view_changelog" == "y" ]
	then
	  clear
	  tac Last_CHANGELOG
	fi
	if [ "$view_changelog" == "n" ]
	then
	  echo
	fi
	if [ "$view_changelog" == "*" ]
	then
	  echo -e "$Red_B" " Invalid option" "$NORMAL"
	fi

    	echo -e -n "$Yellow" "Downloading & Insall (y/n)? (default: y):" "$White_B"
    	read proceed_download
	if [ "$proceed_download" == "n" ]
	then
	  exit 0
	fi


    echo
    echo -e "$Red_B" "Downloading & Insall $new_file ..." "$NORMAL"
    echo

    new_file=TNT_$last_ver.zip

    url=https://github.com/NeoCooler/TNT/archive/master.zip
    wget --no-check-certificate $url -O $new_file
    unzip ~/TNT/$new_file -d ~/TNT/
    rm ~/TNT/$new_file
    cp -a ~/TNT/TNT-master/* ~/TNT/
    rm -r ~/TNT/TNT-master
    echo -e "$Red_B" "You need to restart TNT to see update!" "$NORMAL"
  fi
  rm -f Last_CHANGELOG

script/press_enter
