#!/bin/bash

#############################################################################################
#  -----------------------------------                                                      #
#  | ######## ###   ## ########      | Copyright (c) 2013 - NeoTeam (neocooler29@gmail.com) #
#  |    ##    ####  ##    ##         ---                                                    #
#  |    ##    ## ## ##    ##            |-¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸ ¸¸¸           #
#  |    ##    ##  ####    ##         ---    ``` ``` ``` ``` ``` ``` ``` ``` ``` ```***      #
#  |    ##    ##   ###    ##         | TNT(Tools NeoTeam) is 100% free.                     #
#  ----------------------------------- It may not be duplicated for monetary benefit or any #
#                                    other purpose Without the permission of the developer. #
#############################################################################################

version=$1

source script/colors
echo -e "$NORMALE"

source script/check_root

while : 
do
clear
echo -e "$Cyan" "============================================================" "$NORMAL"
echo -e "     $Green_BU"" ToolsNeoTeam V.$version - by NeoCooler aka krisjanne" "$NORMAL"
echo -e "$Cyan" "============================================================" "$NORMAL"
echo -e "$Cyan" "->$NORMAL$White UPDATE MENU$NORMAL"
echo -e "$Magenta"
echo -e "     1 -$White_K Update All Packages.$Magenta"
echo -e "     2 -$White_K Upgrade Systeme Packages.$Magenta"
echo -e "     3 -$White_K Upgrade & install new Systeme Packages.$Magenta"
echo
echo -e "     4 -$White_K Check Ubuntu Release Upgrade.$Magenta"
echo
echo -e "     5 -$White_K Check update for TNT.$Magenta"
echo
echo -e "     x -$White_K Return MAIN MENU.$Magenta"
echo -e "$NORMAL"
echo -e -n "$Yellow" " Choose option:" "$White_B"
read tntopt
echo
echo -e "$NORMAL"

if [ "$?" != "1" ]
then
case "$tntopt" in
	1 ) sudo apt-get update;;
	2 ) sudo apt-get upgrade;;
	3 ) sudo apt-get dist-upgrade;;
	4 ) update/release_upgrade $version; continue;;
	5 ) update/updater $version; continue;;
	x ) clear; exit 0;;
	* ) echo -e "\033[31m Invalid option\033[0m";;
esac
fi
script/press_enter

done
exit 0;
